server:
  port: 8003

#mybatis配置
mybatis:
  type-aliases-package: com.kuang.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


#spring的配置
spring:
  application:
    name: springcloud-provider-dept #3个服务名称一致
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    diver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db03?use Unicode=true&characterEncoding=utf-8
    username: root
    password: 123456


# Eureka配置：配置服务注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/      # 注册中心地址7001-7003
  instance:
    instance-id: springcloud-provider-dept-8003 #修改Eureka上的默认描述信息

#info配置
info:
  app.name: kuangshen-springcloud
  company.name: blog.kuang.study.com
