server:
  port: 7003

#Eureka配置
eureka:
  instance:
    hostname: eureka7003.com #Eureka服务端的实例名称
  client:
    register-with-eureka: false  #表示是否向 Eureka 注册中心注册自己(这个模块本身是服务器,所以不需要)
    fetch-registry: true # fetch-registry如果为false,则表示自己为注册中心,客户端的化为 ture
    service-url: #监控页面
      #单机：defaultZone: http://${eureka.instance.hostname}:${server.port}/erueka/
      #集群（关联）：
      defaultZone: http://eureka7001.com:7001/erueka/,http://eureka7002.com:7002/erueka/